### ISSUE TITLE
 getting a transform error

### ISSUE THREAD

**Issue by rnunziata** [ethz-asl/volumetric_mapping#71] opened 2017-12-03 20:49 UTC
I am getting a transform error
`:Requested transform time older than cache limit`  

If I change the tf_frame parameter to the optical frame rather then the world frame then I do not get the error.

can you help me understand it.

**Comment by helenol** [comment] 2017-12-04 13:36
Can you confirm that the transformation between these two trees exists, either in rviz or using tf tools? http://wiki.ros.org/tf/Debugging%20tools

**Comment by ZacharyTaylor** [comment] 2017-12-04 13:39
Also if you are playing from a bag are you remembering to use "--clock"

**Comment by rnunziata** [comment] 2017-12-04 17:31
Here is the data: Thank you for looking at this.

```
>>  **************************  rosrun tf world openni_rgb_optical_frame

Frames:
Frame: openni_rgb_optical_frame published by unknown_publisher Average Delay: 0.43345 Max Delay: 0.466913

All Broadcasters:
Node: unknown_publisher 2.05562 Hz, Average Delay: 0.43345 Max Delay: 0.466913



RESULTS: for world to openni_rgb_optical_frame
Chain is: world -> openni_rgb_optical_frame
Net delay     avg = 0.711545: max = 0.965144



>> ******************************   roswtf

Loaded plugin tf.tfwtf
Package: ORB_SLAM2
================================================================================
Static checks summary:

No errors or warnings
================================================================================
Beginning tests of your ROS graph. These may take awhile...
analyzing graph...
... done analyzing graph
running graph rules...
... done running graph rules
running tf checks, this will take a second...
... tf checks complete

Online checks summary:

Found 1 warning(s).
Warnings are things that may be just fine, but are sometimes at fault

WARNING The following node subscriptions are unconnected:
 * /octomap_manager:
   * /cam0/camera_info
   * /cam1/camera_info
   * /input_octomap
   * /tf_static
   * /disparity
 * /rviz:
   * /tf_static

```

![rosgraph](https://user-images.githubusercontent.com/5377074/33566726-e0ccbf64-d8ee-11e7-88a8-381144da8b6b.jpg)
![frames](https://user-images.githubusercontent.com/5377074/33566731-e4bb5e64-d8ee-11e7-96f9-bcadf529dedd.jpg)


>> **************************************** launch file
```

<launch>
  <arg name="rviz_cfg"            default="$(find ORB_SLAM2)/launch/config/octomap_manager.rviz" />
  <arg name="depthsystem1"        default="depth2mono.py"/> <!-- depth2sfm.py depth2mono.py -->

  <!-- creates a depth message and publishes image depth and camera info under new topic  conversion-->
  <node pkg="depth2orb" type="$(arg depthsystem1)" name="depth2orb" output="screen">      
    <param name="camera_frame"  value="openni_rgb_optical_frame"/>                       
  </node>

  <!-- estimates camera pose creates a tracking transform for the pose -->
  <node pkg="ORB_SLAM2" type="RGBD" name="rgbd_odometry" 
        args="/home/rjn/catkin_rosmake_ws/src/ORB_SLAM2/Vocabulary/ORBvoc.txt /home/rjn/catkin_rosmake_ws/src/ORB_SLAM2/Examples/RGB-D/TUM1.yaml">   
    <remap from="/camera/rgb/image_raw" to="/conversion/rgb/image"/>  
    <remap from="/camera/depth_registered/image_raw" to="/conversion/depth/image"/>  
    <param name="base_frame"  type="string" value="world" />  
    <param name="camera_frame" type="string" value="openni_rgb_optical_frame" />  
  </node>
    
  <node pkg="nodelet" type="nodelet" name="standalone_nodelet"  args="manager" output="screen"/>
 
  <!-- creates point cloud form depth and image messages -->
  <node pkg="nodelet" type="nodelet" name="points_xyzrgb" args="load depth_image_proc/point_cloud_xyzrgb standalone_nodelet">
    <remap from="rgb/camera_info"             to="/conversion/rgb/camera_info" />  
    <remap from="rgb/image_rect_color"        to="/conversion/rgb/image"/>  
    <remap from="depth_registered/image_rect" to="/conversion/depth/image"/>  
    <remap from="depth_registered/points"     to="/cloud"/>
    <param name="queue_size"    type="int"    value="50"/>     
  </node>
 
  <node  pkg="octomap_world" type="octomap_manager" name="octomap_manager" output="screen">         
    <param name="tf_frame"  type="string" value="world"/>  
    <remap from="pointcloud"     to="/cloud"/>      
    <param name="map_publish_frequency"  type="double" value="5.0"/>     
    <param name="resolution"  type="double" value="0.5"/>   
    <param name="sensor_max_range" type="double" value="1000.0"/>  
    <param name="octomap_file" type="string" value="/home/rjn/.ros/octomap.bt"/>           
  </node> 

  
  <node pkg="rviz" type="rviz" name="rviz" args="-d $(arg rviz_cfg)"/>

</launch>

```

**Comment by helenol** [comment] 2017-12-04 17:49
Thanks a lot for the detailed results! This is very helpful.
I checked, default TF cache should be 10 seconds and your average delay is waaaay lower than that... So the pointcloud is for sure published in the `openni_rgb_optical_frame` frame (that's what's in the header frame_id)?

Looks like the issue is here:
https://github.com/ethz-asl/volumetric_mapping/blob/master/octomap_world/src/octomap_manager.cc#L457

Could you perhaps output what value `timestamp_age` takes here, in addition to `ros::Time::now()` and `time_to_lookup`?

Seems like some kind of clock mismatch, though that would show up in the tf stuff as well.

Actually can you also confirm that the pointcloud published has a timestamp that isn't 0? Perhaps this is the issue.

**Comment by rnunziata** [comment] 2017-12-04 18:03
Here are transforms from rostopic echo /tf ....I will get back to you on the other data  

```
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1512410340
        nsecs: 387207031
      frame_id: world
    child_frame_id: openni_rgb_optical_frame
    transform: 
      translation: 
        x: -0.221373125911
        y: -1.13990700245
        z: 4.0663151741
      rotation: 
        x: 0.0107588595197
        y: -0.0435342013606
        z: -0.0606918633618
        w: 0.997148695657
---
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1512410340
        nsecs: 859630107
      frame_id: world
    child_frame_id: openni_rgb_optical_frame
    transform: 
      translation: 
        x: -0.227462023497
        y: -1.13106560707
        z: 4.07146978378
      rotation: 
        x: 0.0126627749149
        y: -0.0423238945162
        z: -0.0606810133379
        w: 0.997179098294
---
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1512410341
        nsecs: 338864088
      frame_id: world
    child_frame_id: openni_rgb_optical_frame
    transform: 
      translation: 
        x: -0.221434906125
        y: -1.1463881731
        z: 4.0929775238
      rotation: 
        x: 0.0110110701047
        y: -0.0453929583649
        z: -0.0620696405364
        w: 0.996978232441

```

**Comment by rnunziata** [comment] 2017-12-04 19:12
Here is the data:

code modified as follows:
```
  ros::Time time_to_lookup = timestamp;
  // If this transform isn't possible at the time, then try to just look up
  // the latest (this is to work with bag files and static transform publisher,
  // etc).
  if (!tf_listener_.canTransform(to_frame, from_frame, time_to_lookup)) {
    ros::Duration timestamp_age = ros::Time::now() - time_to_lookup;    
    std::cout << "timestamp_age:" << timestamp_age << std::endl; 
    std::cout << "tf_listener_.getCacheLength():" << tf_listener_.getCacheLength() << std::endl;
    if (timestamp_age < tf_listener_.getCacheLength()) {
      time_to_lookup = ros::Time(0);
      std::cout << "time_to_lookup:" << time_to_lookup << std::endl;      
      ROS_WARN("Using latest TF transform instead of timestamp match.");
    } else {
      ROS_ERROR("Requested transform time older than cache limit.");
      return false;
    }
  }
```


```

timestamp_age:0.367518666
tf_listener_.getCacheLength():10.000000000
time_to_lookup:0.000000000
[ WARN] [1512414412.624965578]: Using latest TF transform instead of timestamp match.
[ERROR] [1512414412.625065060]: Error getting TF transform from sensor data: "world" passed to lookupTransform argument target_frame does not exist. 
init done
timestamp_age:0.633782459
tf_listener_.getCacheLength():10.000000000
time_to_lookup:0.000000000
[ WARN] [1512414413.332055302]: Using latest TF transform instead of timestamp match.
[ERROR] [1512414413.332107236]: Error getting TF transform from sensor data: "world" passed to lookupTransform argument target_frame does not exist. 
timestamp_age:0.467275394
tf_listener_.getCacheLength():10.000000000
time_to_lookup:0.000000000
[ WARN] [1512414413.671613745]: Using latest TF transform instead of timestamp match.
[ERROR] [1512414413.671656507]: Error getting TF transform from sensor data: "world" passed to lookupTransform argument target_frame does not exist. 
timestamp_age:10.864340061
tf_listener_.getCacheLength():10.000000000
[ERROR] [1512414434.250803768]: Requested transform time older than cache limit.
timestamp_age:10.745764127
tf_listener_.getCacheLength():10.000000000
[ERROR] [1512414435.076634603]: Requested transform time older than cache limit.
timestamp_age:11.196118231
tf_listener_.getCacheLength():10.000000000
[ERROR] [1512414436.496100405]: Requested transform time older than cache limit.
timestamp_age:10.733641496
tf_listener_.getCacheLength():10.000000000
[ERROR] [1512414436.496839672]: Requested transform time older than cache limit.
```

**Comment by rnunziata** [comment] 2017-12-04 20:20
I noticed that you use a robot_frame. I had not set this so set it in the launch file as follows but I still bet the error. note I do not have a robot only world to sensor frame.

    <param name="robot_frame"  type="string" value="openni_rgb_optical_frame"/>

**Comment by rnunziata** [comment] 2017-12-04 21:39
This does appear to be a timing issue...I have another set up using rgbdtam rather then orbslam2 and it get intermittent errors of this kind. But how to fix it?

```
timestamp_age:9.725687321
tf_listener_.getCacheLength():10.000000000
time_to_lookup:1512423247.665503978
[ WARN] [1512423257.391219967]: Using latest TF transform instead of timestamp match.
timestamp_age:9.848682474
tf_listener_.getCacheLength():10.000000000
time_to_lookup:1512423248.235579013
[ WARN] [1512423258.084298435]: Using latest TF transform instead of timestamp match.
timestamp_age:9.995339474
tf_listener_.getCacheLength():10.000000000
time_to_lookup:1512423248.795727014
[ WARN] [1512423258.791107760]: Using latest TF transform instead of timestamp match.
timestamp_age:10.160503842
tf_listener_.getCacheLength():10.000000000
[ERROR] [1512423259.521044326]: Requested transform time older than cache limit.
timestamp_age:9.685883744
tf_listener_.getCacheLength():10.000000000
time_to_lookup:1512423249.838351011
[ WARN] [1512423259.525193177]: Using latest TF transform instead of timestamp match.
timestamp_age:10.057639048
tf_listener_.getCacheLength():10.000000000
[ERROR] [1512423260.338165630]: Requested transform time older than cache limit.
timestamp_age:9.623306564
tf_listener_.getCacheLength():10.000000000
time_to_lookup:1512423250.717992067
[ WARN] [1512423260.342350999]: Using latest TF transform instead of timestamp match.
timestamp_age:9.977230436
tf_listener_.getCacheLength():10.000000000
time_to_lookup:1512423251.158112049
[ WARN] [1512423261.136196435]: Using latest TF transform instead of timestamp match.
timestamp_age:10.292460413
tf_listener_.getCacheLength():10.000000000
[ERROR] [1512423261.894162839]: Requested transform time older than cache limit.

```

**Comment by rnunziata** [comment] 2017-12-05 00:31
I placed a print at the end of the routine as follows:

```
  std::cout << "TAKING ACTION" << std::endl;
  tf::transformTFToKindr(tf_transform, transform);
  return true;
```

I only get the error in question a small percent of the time....unless you believe this is an issue you can close this issue.



```
[ERROR] [1512433612.597643949]: Requested transform time older than cache limit.
timestamp_age:10.596840875
tf_listener_.getCacheLength():10.000000000
[ERROR] [1512433612.599501765]: Requested transform time older than cache limit.
TAKING ACTION
TAKING ACTION
timestamp_age:10.628766257
tf_listener_.getCacheLength():10.000000000
[ERROR] [1512433614.090030992]: Requested transform time older than cache limit.
TAKING ACTION
TAKING ACTION
timestamp_age:11.192089665
tf_listener_.getCacheLength():10.000000000
[ERROR] [1512433616.162358262]: Requested transform time older than cache limit.
timestamp_age:10.709294719
tf_listener_.getCacheLength():10.000000000
[ERROR] [1512433616.163063221]: Requested transform time older than cache limit.
TAKING ACTION
TAKING ACTION
timestamp_age:10.527347800
tf_listener_.getCacheLength():10.000000000
[ERROR] [1512433617.437638642]: Requested transform time older than cache limit.
TAKING ACTION
TAKING ACTION
TAKING ACTION
TAKING ACTION
TAKING ACTION
TAKING ACTION
TAKING ACTION
TAKING ACTION
TAKING ACTION
TAKING ACTION
TAKING ACTION
TAKING ACTION
TAKING ACTION
TAKING ACTION
timestamp_age:10.945845932
tf_listener_.getCacheLength():10.000000000
[ERROR] [1512433626.924413153]: Requested transform time older than cache limit.
TAKING ACTION
TAKING ACTION
TAKING ACTION
TAKING ACTION
timestamp_age:10.864235805
tf_listener_.getCacheLength():10.000000000
[ERROR] [1512433629.271331628]: Requested transform time older than cache limit.
TAKING ACTION
TAKING ACTION
TAKING ACTION
TAKING ACTION
TAKING ACTION
timestamp_age:10.8280
```

**Comment by helenol** [comment] 2017-12-05 09:14
I think what's going on here is that it's taking too long to process the pointclouds (since some do get processed). There's two possible solutions to this: one, change the queue size inthe pointcloud subscriber to be shorter (so that more pointclouds are dropped rather than processed 10 seconds late). The other is to increase the queue length for TF, but will probably just make the issue worse since it will get further and further behind.

The queue size is here, set to 40:
https://github.com/ethz-asl/volumetric_mapping/blob/master/octomap_world/src/octomap_manager.cc#L188-L189

If you set it to 1, it'll only use the latest pointcloud coming in and drop the rest :)

Thanks for being so thorough with the debugging! It's incredibly helpful. I'll close this issue since I think we got the cause down.

**Closed by helenol** 2017-12-05 09:14 UTC

**Comment by rnunziata** [comment] 2017-12-05 16:34
Followup...changing point cloud queue size did not help . The system processes the first 30 or so messages without errors then starts getting the timing errors there after. Also reducing the queue size did not make it worse.
